name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job:
    name: Test (Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install project dependencies
        run: pip install poetry && poetry install
      - name: Test code's formatting (Black)
        run: black --check docs tests pandas_dataclasses
      - name: Test code's typing (Pyright)
        run: pyright docs tests pandas_dataclasses
      - name: Test code's typing (mypy)
        run: mypy docs tests pandas_dataclasses
      - name: Test code's execution (pytest)
        run: pytest -v tests
      - name: Test docs' building (Sphinx)
        if: ${{ contains('3.10, 3.11', matrix.python) }}
        run: docs/build
